default: &default
  pool: 5
  timeout: 5000
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  adapter: mysql2
  database: crawler_development
  username: root
  password:
  host: localhost


production:
  <<: *default
  adapter: mysql2
  database: cralwer_production
  username: root
  password: jian.chen
  host: localhost

