default: &DEFAULTS
  host: localhost
  port: 6379

development:
  <<: *DEFAULTS
  namespace: skymatters_dev

production:
  <<: *DEFAULTS
  namespace: skymatters_prod

production:
  <<: *DEFAULTS
  namespace: skymatters_alicloud

demo:
  <<: *DEFAULTS
  namespace: skymatters_demo

staing:
  <<: *DEFAULTS
  namespace: skymatters_stag

test:
  <<: *DEFAULTS
  namespace: skymatters_test
