default: &DEFAULTS
  host: r-uf6a738cd1a60274.redis.rds.aliyuncs.com
  password: DVg0ZurdT2s
  port: 6379

development:
  <<: *DEFAULTS
  namespace: skymatters

production:
  <<: *DEFAULTS
  namespace: skymatters

