# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436522e8ae85ea9d802723d4736a96a832cf5ce2db22b5a8132522476b1b3f89fc31f4a7c330aeaa3f9b295bd6597ac1a3b11d35d0c6f402c4ad7923e9d6edf0

test:
  secret_key_base: cf54c6acb0fd0771086955cdddb264bdee0561be9edabefd7956428040b7e38e26d6ad62e3812e265a744f5d0fe212d1501e5e8619cbb5b75fadb30817bde697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
